In [1]:
import os
os.listdir()

['.ipynb_checkpoints',
 'importing_file.ipynb',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx']

In [3]:
import pandas
dr1 = pandas.read_csv("supermarkets.csv")
dr1

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [4]:
dr2 = pandas.read_json("supermarkets.json")
dr2

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [5]:
dr3 = pandas.read_excel("supermarkets.xlsx" , sheet_name = 0)
dr3

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [6]:
dr4 = pandas.read_csv("supermarkets-commas.txt")
dr4

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [18]:
dr5 = pandas.read_csv("supermarkets-semi-colons.txt" , sep=',')
dr5

ID;Address;City;State;Country;Name;Employees
0  1;3666 21st St;San Francisco;CA 94114;USA;Made...
1  2;735 Dolores St;San Francisco;CA 94119;USA;Br...
2  3;332 Hill St;San Francisco;California 94114;U...
3  4;3995 23rd St;San Francisco;CA 94114;USA;Ben'...
4  5;1056 Sanchez St;San Francisco;California;USA...
5  6;551 Alvarado St;San Francisco;CA 94114;USA;R...

In [19]:
os.listdir()

['.ipynb_checkpoints',
 'head.csv',
 'importing_file.ipynb',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx']

In [33]:
dr6 = pandas.read_csv("head.csv" , header = None)
dr6

0                1              2                 3    4            5   6
0  1     3666 21st St  San Francisco          CA 94114  USA      Madeira   8
1  2   735 Dolores St  San Francisco          CA 94119  USA  Bready Shop  15
2  3      332 Hill St  San Francisco  California 94114  USA  Super River  25
3  4     3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop  10
4  5  1056 Sanchez St  San Francisco        California  USA      Sanchez  12
5  6  551 Alvarado St  San Francisco          CA 94114  USA   Richvalley  20

In [34]:
dr6.columns = ["Numbers" , "Address" , "City" , "Pincode" ,"Country" ,"Landark" , "Order ID"]
dr6

Numbers          Address           City           Pincode Country  \
0        1     3666 21st St  San Francisco          CA 94114     USA   
1        2   735 Dolores St  San Francisco          CA 94119     USA   
2        3      332 Hill St  San Francisco  California 94114     USA   
3        4     3995 23rd St  San Francisco          CA 94114     USA   
4        5  1056 Sanchez St  San Francisco        California     USA   
5        6  551 Alvarado St  San Francisco          CA 94114     USA   

       Landark  Order ID  
0      Madeira         8  
1  Bready Shop        15  
2  Super River        25  
3   Ben's Shop        10  
4      Sanchez        12  
5   Richvalley        20

In [38]:
dr6.set_index("Numbers")

Address           City           Pincode Country  \
Numbers                                                             
1           3666 21st St  San Francisco          CA 94114     USA   
2         735 Dolores St  San Francisco          CA 94119     USA   
3            332 Hill St  San Francisco  California 94114     USA   
4           3995 23rd St  San Francisco          CA 94114     USA   
5        1056 Sanchez St  San Francisco        California     USA   
6        551 Alvarado St  San Francisco          CA 94114     USA   

             Landark  Order ID  
Numbers                         
1            Madeira         8  
2        Bready Shop        15  
3        Super River        25  
4         Ben's Shop        10  
5            Sanchez        12  
6         Richvalley        20

In [4]:
dr7 = dr6.set_index("Numbers")
dr7

NameError: name 'dr6' is not defined

In [43]:
dr7

Address           City           Pincode Country  \
Numbers                                                             
1           3666 21st St  San Francisco          CA 94114     USA   
2         735 Dolores St  San Francisco          CA 94119     USA   
3            332 Hill St  San Francisco  California 94114     USA   
4           3995 23rd St  San Francisco          CA 94114     USA   
5        1056 Sanchez St  San Francisco        California     USA   
6        551 Alvarado St  San Francisco          CA 94114     USA   

             Landark  Order ID  
Numbers                         
1            Madeira         8  
2        Bready Shop        15  
3        Super River        25  
4         Ben's Shop        10  
5            Sanchez        12  
6         Richvalley        20

In [82]:
dr7.drop( dr7.columns[1:5], 1)

Address  Order ID
Numbers                           
1           3666 21st St         8
2         735 Dolores St        15
3            332 Hill St        25
4           3995 23rd St        10
5        1056 Sanchez St        12
6        551 Alvarado St        20

In [6]:
import os
os.listdir()

['.ipynb_checkpoints',
 'head.csv',
 'importing_file.ipynb',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx']

In [10]:
import pandas
dr6 = pandas.read_csv("supermarkets.csv")
dr6

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [14]:
dr6["Zipcode"]  =dr6.shape[0]*["132022"]
dr6

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees Zipcode  
0          8  132022  
1         15  132022  
2         25  132022  
3         10  132022  
4         12  132022  
5         20  132022

In [18]:
dr6["Zipcode"] = dr6["City"]+ ","+ "132022"
dr6

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees               Zipcode  
0          8  San Francisco,132022  
1         15  San Francisco,132022  
2         25  San Francisco,132022  
3         10  San Francisco,132022  
4         12  San Francisco,132022  
5         20  San Francisco,132022

In [27]:
dr7 =dr6.T 
dr7

0                     1                     2  \
ID                            1                     2                     3   
Address            3666 21st St        735 Dolores St           332 Hill St   
City              San Francisco         San Francisco         San Francisco   
State                  CA 94114              CA 94119      California 94114   
Country                     USA                   USA                   USA   
Name                    Madeira           Bready Shop           Super River   
Employees                     8                    15                    25   
Zipcode    San Francisco,132022  San Francisco,132022  San Francisco,132022   

                              3                     4                     5  
ID                            4                     5                     6  
Address            3995 23rd St       1056 Sanchez St       551 Alvarado St  
City              San Francisco         San Francisco         San Francisco  
State                  CA 94114            California              CA 94114  
Country                     USA                   USA                   USA  
Name                 Ben's Shop               Sanchez            Richvalley  
Employees                    10                    12                    20  
Zipcode    San Francisco,132022  San Francisco,132022  San Francisco,132022

In [75]:
dr7["100"] = ["001" ,"Dula" ,"Karnal" , "Haryana" , "India" , "Lakshit" , "Gov" , 13320]
dr7

ValueError: Length of values (8) does not match length of index (6)

In [34]:
dr9 = dr7.T

In [35]:
dr9

ID          Address           City             State Country  \
0      1     3666 21st St  San Francisco          CA 94114     USA   
1      2   735 Dolores St  San Francisco          CA 94119     USA   
2      3      332 Hill St  San Francisco  California 94114     USA   
3      4     3995 23rd St  San Francisco          CA 94114     USA   
4      5  1056 Sanchez St  San Francisco        California     USA   
5      6  551 Alvarado St  San Francisco          CA 94114     USA   
100  001             Dula         Karnal           Haryana   India   

            Name Employees               Zipcode  
0        Madeira         8  San Francisco,132022  
1    Bready Shop        15  San Francisco,132022  
2    Super River        25  San Francisco,132022  
3     Ben's Shop        10  San Francisco,132022  
4        Sanchez        12  San Francisco,132022  
5     Richvalley        20  San Francisco,132022  
100      Lakshit       Gov                 13320

In [56]:
dr10 = dr9.drop( dr9.columns[7:], 1)
dr10


ID          Address           City             State Country  \
0      1     3666 21st St  San Francisco          CA 94114     USA   
1      2   735 Dolores St  San Francisco          CA 94119     USA   
2      3      332 Hill St  San Francisco  California 94114     USA   
3      4     3995 23rd St  San Francisco          CA 94114     USA   
4      5  1056 Sanchez St  San Francisco        California     USA   
5      6  551 Alvarado St  San Francisco          CA 94114     USA   
100  001             Dula         Karnal           Haryana   India   

            Name Employees  
0        Madeira         8  
1    Bready Shop        15  
2    Super River        25  
3     Ben's Shop        10  
4        Sanchez        12  
5     Richvalley        20  
100      Lakshit       Gov

In [58]:
dr11 = dr10.T
dr11

0               1                 2              3  \
ID                     1               2                 3              4   
Address     3666 21st St  735 Dolores St       332 Hill St   3995 23rd St   
City       San Francisco   San Francisco     San Francisco  San Francisco   
State           CA 94114        CA 94119  California 94114       CA 94114   
Country              USA             USA               USA            USA   
Name             Madeira     Bready Shop       Super River     Ben's Shop   
Employees              8              15                25             10   

                         4                5      100  
ID                       5                6      001  
Address    1056 Sanchez St  551 Alvarado St     Dula  
City         San Francisco    San Francisco   Karnal  
State           California         CA 94114  Haryana  
Country                USA              USA    India  
Name               Sanchez       Richvalley  Lakshit  
Employees               12               20      Gov

In [62]:
dr8 = dr11.drop(dr11.columns[6:] , 1)
dr8

0               1                 2              3  \
ID                     1               2                 3              4   
Address     3666 21st St  735 Dolores St       332 Hill St   3995 23rd St   
City       San Francisco   San Francisco     San Francisco  San Francisco   
State           CA 94114        CA 94119  California 94114       CA 94114   
Country              USA             USA               USA            USA   
Name             Madeira     Bready Shop       Super River     Ben's Shop   
Employees              8              15                25             10   

                         4                5  
ID                       5                6  
Address    1056 Sanchez St  551 Alvarado St  
City         San Francisco    San Francisco  
State           California         CA 94114  
Country                USA              USA  
Name               Sanchez       Richvalley  
Employees               12               20

In [64]:
dr7 = dr8.T
dr7

ID          Address           City             State Country         Name  \
0  1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1  2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2  3      332 Hill St  San Francisco  California 94114     USA  Super River   
3  4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4  5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5  6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

  Employees  
0         8  
1        15  
2        25  
3        10  
4        12  
5        20

In [68]:
dr7["Zipcode"] = dr7.shape[0]*["132011"]
dr7

ID          Address           City             State Country         Name  \
0  1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1  2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2  3      332 Hill St  San Francisco  California 94114     USA  Super River   
3  4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4  5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5  6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

  Employees Zipcode  
0         8  132011  
1        15  132011  
2        25  132011  
3        10  132011  
4        12  132011  
5        20  132011

In [69]:
dr7["Zipcode"] = dr7["City"] + ","+"123022"
dr7

ID          Address           City             State Country         Name  \
0  1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1  2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2  3      332 Hill St  San Francisco  California 94114     USA  Super River   
3  4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4  5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5  6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

  Employees               Zipcode  
0         8  San Francisco,123022  
1        15  San Francisco,123022  
2        25  San Francisco,123022  
3        10  San Francisco,123022  
4        12  San Francisco,123022  
5        20  San Francisco,123022

In [70]:
dr8 = dr7.T
dr8

0                     1                     2  \
ID                            1                     2                     3   
Address            3666 21st St        735 Dolores St           332 Hill St   
City              San Francisco         San Francisco         San Francisco   
State                  CA 94114              CA 94119      California 94114   
Country                     USA                   USA                   USA   
Name                    Madeira           Bready Shop           Super River   
Employees                     8                    15                    25   
Zipcode    San Francisco,123022  San Francisco,123022  San Francisco,123022   

                              3                     4                     5  
ID                            4                     5                     6  
Address            3995 23rd St       1056 Sanchez St       551 Alvarado St  
City              San Francisco         San Francisco         San Francisco  
State                  CA 94114            California              CA 94114  
Country                     USA                   USA                   USA  
Name                 Ben's Shop               Sanchez            Richvalley  
Employees                    10                    12                    20  
Zipcode    San Francisco,123022  San Francisco,123022  San Francisco,123022

In [78]:
dr8[2] = ["121" , "kkl" , "arl", "HHr" , "Zco" , "llr" , "Gov " , 124]
dr8

0                     1     2  \
ID                            1                     2   121   
Address            3666 21st St        735 Dolores St   kkl   
City              San Francisco         San Francisco   arl   
State                  CA 94114              CA 94119   HHr   
Country                     USA                   USA   Zco   
Name                    Madeira           Bready Shop   llr   
Employees                     8                    15  Gov    
Zipcode    San Francisco,123022  San Francisco,123022   124   

                              3                     4         5       100  \
ID                            4                     5       001       001   
Address            3995 23rd St       1056 Sanchez St       Gtg       Gtg   
City              San Francisco         San Francisco  New York  New York   
State                  CA 94114            California        Us        Us   
Country                     USA                   USA       Usa       Usa   
Name                 Ben's Shop               Sanchez   Lakshit   Lakshit   
Employees                    10                    12       Gov       Gov   
Zipcode    San Francisco,123022  San Francisco,123022    123123    123123   

                  5  
ID              001  
Address         Gtg  
City       New York  
State            Us  
Country         Usa  
Name        Lakshit  
Employees       Gov  
Zipcode      123123

In [79]:
dr9 = dr8.T

In [80]:
dr9

ID          Address           City       State Country         Name  \
0      1     3666 21st St  San Francisco    CA 94114     USA      Madeira   
1      2   735 Dolores St  San Francisco    CA 94119     USA  Bready Shop   
2    121              kkl            arl         HHr     Zco          llr   
3      4     3995 23rd St  San Francisco    CA 94114     USA   Ben's Shop   
4      5  1056 Sanchez St  San Francisco  California     USA      Sanchez   
5    001              Gtg       New York          Us     Usa      Lakshit   
100  001              Gtg       New York          Us     Usa      Lakshit   
5    001              Gtg       New York          Us     Usa      Lakshit   

    Employees               Zipcode  
0           8  San Francisco,123022  
1          15  San Francisco,123022  
2        Gov                    124  
3          10  San Francisco,123022  
4          12  San Francisco,123022  
5         Gov                123123  
100       Gov                123123  
5         Gov                123123

In [81]:
import geopy
dir(geopy)

['AlgoliaPlaces',
 'ArcGIS',
 'AzureMaps',
 'BANFrance',
 'Baidu',
 'BaiduV3',
 'Bing',
 'DataBC',
 'GeoNames',
 'GeocodeEarth',
 'GeocodeFarm',
 'Geolake',
 'GoogleV3',
 'Here',
 'IGNFrance',
 'LiveAddress',
 'Location',
 'MapBox',
 'MapQuest',
 'MapTiler',
 'Nominatim',
 'OpenCage',
 'OpenMapQuest',
 'Pelias',
 'Photon',
 'PickPoint',
 'Point',
 'Timezone',
 'TomTom',
 'What3Words',
 'Yandex',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '__version_info__',
 'adapters',
 'compat',
 'exc',
 'format',
 'geocoders',
 'get_geocoder_for_service',
 'get_version',
 'location',
 'point',
 'timezone',
 'units',
 'util']

In [82]:
from geopy import ArcGIS

In [83]:
nun = ArcGIS()

In [86]:
loc = nun.geocode(" 3666 21st St, San Francisco, CA 94114 ")
loc

Location(3666 21st St, San Francisco, California, 94114, (37.756648011392286, -122.42937496976432, 0.0))

In [90]:
loc.latitude

37.756648011392286

In [91]:
loc.longitude

-122.42937496976432

In [92]:
dr7

ID          Address           City             State Country         Name  \
0  1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1  2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2  3      332 Hill St  San Francisco  California 94114     USA  Super River   
3  4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4  5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5  6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

  Employees               Zipcode  
0         8  San Francisco,123022  
1        15  San Francisco,123022  
2        25  San Francisco,123022  
3        10  San Francisco,123022  
4        12  San Francisco,123022  
5        20  San Francisco,123022

In [95]:
dr7["Address"] = dr7["Address"]+","+dr7["City"]+","+dr7["State"]

In [96]:
dr7

ID                                     Address           City  \
0  1         3666 21st St,San Francisco,CA 94114  San Francisco   
1  2       735 Dolores St,San Francisco,CA 94119  San Francisco   
2  3  332 Hill St,San Francisco,California 94114  San Francisco   
3  4         3995 23rd St,San Francisco,CA 94114  San Francisco   
4  5    1056 Sanchez St,San Francisco,California  San Francisco   
5  6      551 Alvarado St,San Francisco,CA 94114  San Francisco   

              State Country         Name Employees               Zipcode  
0          CA 94114     USA      Madeira         8  San Francisco,123022  
1          CA 94119     USA  Bready Shop        15  San Francisco,123022  
2  California 94114     USA  Super River        25  San Francisco,123022  
3          CA 94114     USA   Ben's Shop        10  San Francisco,123022  
4        California     USA      Sanchez        12  San Francisco,123022  
5          CA 94114     USA   Richvalley        20  San Francisco,123022

In [97]:
dr7["Coordinates"] = dr7["Address"].apply(nun.geocode)

In [98]:
dr7

ID                                     Address           City  \
0  1         3666 21st St,San Francisco,CA 94114  San Francisco   
1  2       735 Dolores St,San Francisco,CA 94119  San Francisco   
2  3  332 Hill St,San Francisco,California 94114  San Francisco   
3  4         3995 23rd St,San Francisco,CA 94114  San Francisco   
4  5    1056 Sanchez St,San Francisco,California  San Francisco   
5  6      551 Alvarado St,San Francisco,CA 94114  San Francisco   

              State Country         Name Employees               Zipcode  \
0          CA 94114     USA      Madeira         8  San Francisco,123022   
1          CA 94119     USA  Bready Shop        15  San Francisco,123022   
2  California 94114     USA  Super River        25  San Francisco,123022   
3          CA 94114     USA   Ben's Shop        10  San Francisco,123022   
4        California     USA      Sanchez        12  San Francisco,123022   
5          CA 94114     USA   Richvalley        20  San Francisco,123022   

                                         Coordinates  
0  (3666 21st St, San Francisco, California, 9411...  
1  (735 Dolores St, San Francisco, California, 94...  
2  (332 Hill St, San Francisco, California, 94114...  
3  (3995 23rd St, San Francisco, California, 9411...  
4  (1056 Sanchez St, San Francisco, California, 9...  
5  (551 Alvarado St, San Francisco, California, 9...

In [101]:
dr7["Latitude"] = dr7["Coordinates"].apply(lambda x: x.latitude if x!=None else None)

In [102]:
dr7

ID                                     Address           City  \
0  1         3666 21st St,San Francisco,CA 94114  San Francisco   
1  2       735 Dolores St,San Francisco,CA 94119  San Francisco   
2  3  332 Hill St,San Francisco,California 94114  San Francisco   
3  4         3995 23rd St,San Francisco,CA 94114  San Francisco   
4  5    1056 Sanchez St,San Francisco,California  San Francisco   
5  6      551 Alvarado St,San Francisco,CA 94114  San Francisco   

              State Country         Name Employees               Zipcode  \
0          CA 94114     USA      Madeira         8  San Francisco,123022   
1          CA 94119     USA  Bready Shop        15  San Francisco,123022   
2  California 94114     USA  Super River        25  San Francisco,123022   
3          CA 94114     USA   Ben's Shop        10  San Francisco,123022   
4        California     USA      Sanchez        12  San Francisco,123022   
5          CA 94114     USA   Richvalley        20  San Francisco,123022   

                                         Coordinates   Latitude  
0  (3666 21st St, San Francisco, California, 9411...  37.756648  
1  (735 Dolores St, San Francisco, California, 94...  37.757819  
2  (332 Hill St, San Francisco, California, 94114...  37.755875  
3  (3995 23rd St, San Francisco, California, 9411...  37.752922  
4  (1056 Sanchez St, San Francisco, California, 9...  37.752131  
5  (551 Alvarado St, San Francisco, California, 9...  37.753511

In [103]:
dr7["Longitude"] = dr7["Coordinates"].apply(lambda x: x.longitude if x!= None else None)
dr7

ID                                     Address           City  \
0  1         3666 21st St,San Francisco,CA 94114  San Francisco   
1  2       735 Dolores St,San Francisco,CA 94119  San Francisco   
2  3  332 Hill St,San Francisco,California 94114  San Francisco   
3  4         3995 23rd St,San Francisco,CA 94114  San Francisco   
4  5    1056 Sanchez St,San Francisco,California  San Francisco   
5  6      551 Alvarado St,San Francisco,CA 94114  San Francisco   

              State Country         Name Employees               Zipcode  \
0          CA 94114     USA      Madeira         8  San Francisco,123022   
1          CA 94119     USA  Bready Shop        15  San Francisco,123022   
2  California 94114     USA  Super River        25  San Francisco,123022   
3          CA 94114     USA   Ben's Shop        10  San Francisco,123022   
4        California     USA      Sanchez        12  San Francisco,123022   
5          CA 94114     USA   Richvalley        20  San Francisco,123022   

                                         Coordinates   Latitude   Longitude  
0  (3666 21st St, San Francisco, California, 9411...  37.756648 -122.429375  
1  (735 Dolores St, San Francisco, California, 94...  37.757819 -122.425337  
2  (332 Hill St, San Francisco, California, 94114...  37.755875 -122.428816  
3  (3995 23rd St, San Francisco, California, 9411...  37.752922 -122.431697  
4  (1056 Sanchez St, San Francisco, California, 9...  37.752131 -122.430028  
5  (551 Alvarado St, San Francisco, California, 9...  37.753511 -122.433229

In [7]:
import os
os.listdir()

['.ipynb_checkpoints',
 'head.csv',
 'importing_file.ipynb',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx']

In [10]:
import pandas
dr7 = pandas.read_csv("supermarkets.csv")
dr7

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [11]:
import geopy  

In [12]:
from geopy import ArcGIS

In [14]:
help(geopy.ArcGIS)

Help on class ArcGIS in module geopy.geocoders.arcgis:

class ArcGIS(geopy.geocoders.base.Geocoder)
 |  ArcGIS(username=None, password=None, *, referer=None, token_lifetime=60, scheme=None, timeout=DEFAULT_SENTINEL, proxies=DEFAULT_SENTINEL, user_agent=None, ssl_context=DEFAULT_SENTINEL, adapter_factory=None, auth_domain='www.arcgis.com', domain='geocode.arcgis.com')
 |  
 |  Geocoder using the ERSI ArcGIS API.
 |  
 |  Documentation at:
 |      https://developers.arcgis.com/rest/geocode/api-reference/overview-world-geocoding-service.htm
 |  
 |  Method resolution order:
 |      ArcGIS
 |      geopy.geocoders.base.Geocoder
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, username=None, password=None, *, referer=None, token_lifetime=60, scheme=None, timeout=DEFAULT_SENTINEL, proxies=DEFAULT_SENTINEL, user_agent=None, ssl_context=DEFAULT_SENTINEL, adapter_factory=None, auth_domain='www.arcgis.com', domain='geocode.arcgis.com')
 |      :param str username: Ar

In [15]:
nun = ArcGIS()

In [17]:
loc = nun.geocode("3666 21st St,San Francisco,CA94114")
loc

Location(3666 21st St, San Francisco, California, 94114, (37.756648011392286, -122.42937496976432, 0.0))

In [20]:
loc.latitude

37.756648011392286

In [21]:
dr7["Address"] = dr7["Address"] +","+dr7["City"] + "," +["State"]

In [22]:
dr7

ID                              Address           City             State  \
0   1     3666 21st St,San Francisco,State  San Francisco          CA 94114   
1   2   735 Dolores St,San Francisco,State  San Francisco          CA 94119   
2   3      332 Hill St,San Francisco,State  San Francisco  California 94114   
3   4     3995 23rd St,San Francisco,State  San Francisco          CA 94114   
4   5  1056 Sanchez St,San Francisco,State  San Francisco        California   
5   6  551 Alvarado St,San Francisco,State  San Francisco          CA 94114   

  Country         Name  Employees  
0     USA      Madeira          8  
1     USA  Bready Shop         15  
2     USA  Super River         25  
3     USA   Ben's Shop         10  
4     USA      Sanchez         12  
5     USA   Richvalley         20

In [23]:
dr7["Coordinates"] = dr7["Address"].apply(nun.geocode)

In [25]:
dr7

ID                              Address           City             State  \
0   1     3666 21st St,San Francisco,State  San Francisco          CA 94114   
1   2   735 Dolores St,San Francisco,State  San Francisco          CA 94119   
2   3      332 Hill St,San Francisco,State  San Francisco  California 94114   
3   4     3995 23rd St,San Francisco,State  San Francisco          CA 94114   
4   5  1056 Sanchez St,San Francisco,State  San Francisco        California   
5   6  551 Alvarado St,San Francisco,State  San Francisco          CA 94114   

  Country         Name  Employees  \
0     USA      Madeira          8   
1     USA  Bready Shop         15   
2     USA  Super River         25   
3     USA   Ben's Shop         10   
4     USA      Sanchez         12   
5     USA   Richvalley         20   

                                         Coordinates  
0  (3666 21st St, San Francisco, California, 9411...  
1  (735 Dolores St, San Francisco, California, 94...  
2  (332 Hill St, San Francisco, California, 94114...  
3  (3995 23rd St, San Francisco, California, 9411...  
4  (1056 Sanchez St, San Francisco, California, 9...  
5  (551 Alvarado St, San Francisco, California, 9...

In [37]:
dr7.Coordinates[0].latitude

37.756648011392286

In [38]:
dr7["Latitude"] = dr7["Coordinates"].apply(lambda x: x.latitude if x != None else None)

In [39]:
dr7

ID                              Address           City             State  \
0   1     3666 21st St,San Francisco,State  San Francisco          CA 94114   
1   2   735 Dolores St,San Francisco,State  San Francisco          CA 94119   
2   3      332 Hill St,San Francisco,State  San Francisco  California 94114   
3   4     3995 23rd St,San Francisco,State  San Francisco          CA 94114   
4   5  1056 Sanchez St,San Francisco,State  San Francisco        California   
5   6  551 Alvarado St,San Francisco,State  San Francisco          CA 94114   

  Country         Name  Employees  \
0     USA      Madeira          8   
1     USA  Bready Shop         15   
2     USA  Super River         25   
3     USA   Ben's Shop         10   
4     USA      Sanchez         12   
5     USA   Richvalley         20   

                                         Coordinates   Latitude  
0  (3666 21st St, San Francisco, California, 9411...  37.756648  
1  (735 Dolores St, San Francisco, California, 94...  37.757819  
2  (332 Hill St, San Francisco, California, 94114...  37.755875  
3  (3995 23rd St, San Francisco, California, 9411...  37.752922  
4  (1056 Sanchez St, San Francisco, California, 9...  37.752131  
5  (551 Alvarado St, San Francisco, California, 9...  37.753511

In [40]:
dr7["Longitude"] = dr7["Coordinates"].apply(lambda x: x.longitude if x != None else None)

In [41]:
dr7

ID                              Address           City             State  \
0   1     3666 21st St,San Francisco,State  San Francisco          CA 94114   
1   2   735 Dolores St,San Francisco,State  San Francisco          CA 94119   
2   3      332 Hill St,San Francisco,State  San Francisco  California 94114   
3   4     3995 23rd St,San Francisco,State  San Francisco          CA 94114   
4   5  1056 Sanchez St,San Francisco,State  San Francisco        California   
5   6  551 Alvarado St,San Francisco,State  San Francisco          CA 94114   

  Country         Name  Employees  \
0     USA      Madeira          8   
1     USA  Bready Shop         15   
2     USA  Super River         25   
3     USA   Ben's Shop         10   
4     USA      Sanchez         12   
5     USA   Richvalley         20   

                                         Coordinates   Latitude   Longitude  
0  (3666 21st St, San Francisco, California, 9411...  37.756648 -122.429375  
1  (735 Dolores St, San Francisco, California, 94...  37.757819 -122.425337  
2  (332 Hill St, San Francisco, California, 94114...  37.755875 -122.428816  
3  (3995 23rd St, San Francisco, California, 9411...  37.752922 -122.431697  
4  (1056 Sanchez St, San Francisco, California, 9...  37.752131 -122.430028  
5  (551 Alvarado St, San Francisco, California, 9...  37.753511 -122.433229

In [42]:
[[1 ,2,3],[1,2,3,4,5]]

[[1, 2, 3], [1, 2, 3, 4, 5]]

In [43]:
import numpy
arr = numpy.arange(27)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [46]:
n = arr.reshape(3,3,3)

In [47]:
n

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [55]:
import cv2
img = cv2.imread("img.png", 0)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 21, 21, 21, 21],
       [ 0,  0,  0, 21, 21, 21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21, 21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21, 21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21, 21, 28, 28, 28, 28],
       [21, 21, 21, 21, 21, 21, 28, 28, 28, 28],
       [21, 21, 21, 21, 21, 21, 28, 28, 28, 28]], dtype=uint8)

In [56]:
cv2.imwrite("newimg.png", n )


True

In [73]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [75]:
for i in n.T:
    print(i)

[[ 0  9 18]
 [ 3 12 21]
 [ 6 15 24]]
[[ 1 10 19]
 [ 4 13 22]
 [ 7 16 25]]
[[ 2 11 20]
 [ 5 14 23]
 [ 8 17 26]]


In [77]:
n[0:2,0:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 9, 10, 11],
        [12, 13, 14]]])

In [78]:
for i in n.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [107]:
zee = numpy.hstack((n,n,n))
zee

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [110]:
spp = numpy.vsplit(zee,3)
spp

[array([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8],
         [0, 1, 2],
         [3, 4, 5],
         [6, 7, 8],
         [0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]]),
 array([[[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17],
         [ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17],
         [ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]]),
 array([[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])]